### ISSUE TITLE
BIDS eyetracking data

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/studyforrest-data#12]
The BEP20 extension proposal isn't yet merged (https://docs.google.com/document/d/1eggzTCzSHG3AEKhtnEDbcdk-2avXN6I94X8aUPEBVsw/edit#heading=h.9tphvz6ot0j1), but better than when I last looked at it. Its probably a good idea to check which metadata they recommend and require, and as far as I can see from a quick browse through BIDS 1.5.0, the json sidecar files for eyetracking data are yet missing.

**Comment by adswa** [comment]
Relevant metadata:

MUST:
``TaskName``
SHOULD:
````
````
````
````

**Comment by adswa** [comment]
As it is not yet clear where this information needs to go, I am collecting all of the pieces in this issue:

- BIDS BEP20 is not yet merged, and does not appear to be to close to a merge - let's comply to BIDS 1.6 as best as possible (using the Physiological and other continuous recordings specification)
- Currently, the eyetracking data consists of two files, of which the first complies to BIDS naming conventions:
   - ``sub-<int>/ses-<id>/func/sub-<id>_ses-<id>_task-<id>_run-<int>_recording-eyegaze_physio.tsv.gz``
   - ``sub-<int>/ses-<id>/func/sub-<id>_ses-<id>_task-<id>_run-<int>_eyelinkraw.asc.gz``
- The raw eyelink ``.asc`` file is not BIDS-compliant and breaks the validator, it is also not included in the studyforrest dataset on OpenNeuro. However, it is a part of the data descriptor (i.e., mentioned in the publication). I propose to move it in a ``sourcedata`` folder. Any thoughts/arguments against ?
   - [ ] ~TODO: move raw Eyelink data to a ``sourcedata/`` directory~
- ``sub-<int>/ses-<id>/func/sub-<id>_ses-<id>_task-<id>_run-<int>_recording-eyegaze_physio.tsv.gz`` lacks a JSON sidecar file ``sub-<int>/ses-<id>/func/sub-<id>_ses-<id>_task-<id>_run-<int>_recording-eyegaze_physio.json``. We should include the following fields (based on a mix of currently required values, and required values from BEP20 that are sensible to include):
  ```
  "SamplingFrequency": 1000,
  "Columns": ["x_coordinate", "y_coordinate", "pupil_size", "frame_id"],
  "SampleCoordinateUnit": "pixel",
  "SampleCoordinateSystem": "gaze-on-screen",
  "EnvironmentCoordinates": [["0,0", "top left"], ["1, 1", "bottom right"]],
  "Manufacturer": "SR-Research",
  "ManufacturerModelName": "Eyelink1000",
  "SoftwareVersion": "4.594"
  ```
    - [ ] ~TODO: Write a script that creates and saves this information as a JSON file~

**Comment by loj** [comment]
re JSON sidecar files: This already exists in a top level file `recording-eyegaze_physio.json` See https://github.com/psychoinformatics-de/studyforrest-data-phase2/issues/17#issuecomment-827352636

re  raw eyelink `.asc` files: If we want to make the BIDS validator happy, I would suggest adding these to a `.bidsignore` file rather than moving them to a `sourcedata/` directory. I would think that it would be more useful to have these alongside the `tsv.gz` files

**Comment by adswa** [comment]
> I would suggest adding these to a .bidsignore file rather than moving them to a sourcedata/ directory

Sounds  good!

**Comment by adswa** [comment]
PR is here: https://github.com/psychoinformatics-de/studyforrest-data-phase2/pull/19

Would you mind taking a look, @loj ?

**Comment by adswa** [comment]
Thanks @loj!
