### ISSUE TITLE
examine data processing of website build

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-data#20]
I know nothing about this, other than (at one point) FSL was needed to process some of the data and turn it into a form usable by Papaya (and possibly other web assets).

The purist in me would love to see no processing just for the website, and either use the raw data (unlikely), or publish the processed data if it's of utility to others.

If, however, the above is not feasible, we should process the data using CI, and stop relying on Michael's laptop configuration from 4 years ago.

**Comment by jsheunis** [comment]
Seems like raw data should be possible to use when it comes to viewing NIfTI data in the browser, although we can check that once we have Papaya running.

For the quality control features there's definitely processing involved:
- For framewise displacement of functional MRI time series, I use Python (with numpy, pandas and plotly) on the raw white-space-delimited text data.
- For the freesurfer parcellation GIF, I used freesurfer, imagemagick and ffmpeg on the freesurfer dataset.
- I might still look at plotting the overlap of (non)linear structural-functional registrations, for which I'm as yet uncertain what processing will be required.

We should discuss what this means for keeping the website lean...
