### ISSUE TITLE
use CI/CD to build and publish website

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-data#21]

**Comment by aqw** [comment]
Open question: what is the preferred CI of psyinf?

Travis is dead to us, so I see the following:

- GitHub Actions
- Appveyor

**Comment by bpoldrack** [comment]
My 2 cents: From my POV, the advantage of AppVeyor is to have VMs running where one can actually login. The number of workers is limited, though. For the purpose of website building GitHub Actions are fine, I guess, and don't put an additional burden on the AppVeyor account.

**Comment by aqw** [comment]
We went with GitHub Actions, as we could copy-paste from the psyinf website build.

This is in the tree, but it has not been confirmed, as it's not yet merged into `master`.

**Comment by aqw** [comment]
I have merged `uplift` into `master`. GitHub Actions work beautifully, and the `gh-pages` branch is populated as intended.

The website itself is not actually live, as the DNS records need to be updated. But everything else is in place.
