### ISSUE TITLE
update hosting acknowledgments

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-data#25]
Studyforrest is currently hosted at FZJ. We should add FZJ (and possibly others, such as Gin #8) to the list.

https://www.studyforrest.org/access.html

List:
- OpenNeuro
- FZJ
- Gin

OvGU no longer hosts the data

**Comment by loj** [comment]
Gin logos: https://gin.g-node.org/G-Node/logos

**Comment by aqw** [comment]
OpenNeuro, FZJ, and Gin are all acknowledged. Anyone else can easily be added. Closing.
