### ISSUE TITLE
Hackathon coordination (projects)

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/studyforrest-data#26]
Here is a list of project that @mih extracted from the individual issues. Feel free to edit the post to extend/alter.

### Redo Website 

Essentially replace the current one, with something that is easier to build, more lightweight, and potentially presents the dataset as more of a "done" thing.

**Subprojects:**
- Website content (e.g., #9, #10, #24, #25)
- Website infrastructure (e.g., #19, #22, #20,  #21)
- Fancy website features (e.g.,  #16, #23)

Coordinator: @aqw 
Co-hackers: @jsheunis maybe @loj @mih maybe @adswa maybe @christian-monch 

### Data Hosting

All aspects related to data hosting.

**Subprojects:**
- DataLad superdataset: This repository shall become a true DataLad superdataset that links all individual pieces of the dataset (raw data, derivatives, contributions) into a intelligible hierarchy, and add the necessary descriptions/metadata for people to discover and understand the dataset. This shall be the subject of the to be written manuscript (#2)
- New data (e.g., #17, #15)
- Maintain exsting data: (e.g., #4, #6, #14, #3 )
- metadata #7 

Coordinator: @loj 
Co-hackers: @adswa , @m-wierzba , @christian-monch (esp metadata), @chrhaeusler (esp annotations)

### BIDS / Release the phase1 data in BIDS format

**Subprojects**
- Reconvert from the old raw data using reproducible means, and verify if and where these new data deviate from the original release.
- other BIDSifications: #13, #12

Coordinator: @bpoldrack 
Co-hackers: maybe @loj maybe @adswa , @m-wierzba 

### The manuscript

Besides the "hey, here is a refreshed studyforrest" aspect, the main focus of the paper can be a DataLad feature. It enables to move into the future (adopt BIDS, change data portal technology) without having to break the static aspects of science (i.e. publications). A brief paper should show how we can benefit from BIDS hosting at OpenNeuro, while retaining an accessible dataset version the matches the data descriptor from 2014 and 2016 one-to-one. This is a non-trivial task, because our reconverted data may be substantially different from their renamed data.

coordinator: @chrhaeusler 
co-hacker: maybe @adswa

**Comment by mih** [comment]
Once discussed, we can turn the accepted projects into actual projects of the management feature of this github repo.

**Comment by adswa** [comment]
I have tried to refine this into subprojects/-topics

**Comment by adswa** [comment]
Needed: A list of resources
- Current OpenNeuro dataset: https://openneuro.org/datasets/ds000113/versions/1.3.0
- Website: https://www.studyforrest.org/
- Website sources: https://github.com/psychoinformatics-de/studyforrest-www
- Phase 1 data on juseless: /data/project/studyforrest/anondata

**Comment by adswa** [comment]
Coordination happens via project board, think we can close this.
