### ISSUE TITLE
explore niivue 

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-data#27]
It's a WebGL based nifti viewer.

If usable, it might be a nice alternative to [Papaya](https://rii-mango.github.io/Papaya/), which we currently use, but is fussy, and currently broken on the website (see #23).

https://github.com/niivue/niivue
https://hanayik.github.io/niivue/

**Comment by jsheunis** [comment]
Another option to look into is Brainsprite, which can be used to generate the html and javascript statically, although it is more limited ito in-browser user functionality.

https://github.com/brainsprite/brainsprite
https://brainsprite.github.io/index.html

**Comment by aqw** [comment]
Won't fix. We're going with NeuroVault instead.
