### ISSUE TITLE
Use DataLad-only access instructions on website and READMEs

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/studyforrest-data#3]
All other means are other outdated, or limited with respect to what is available.

At present the website describes git-annex based access as "geek mode". These times are over.

**Comment by aqw** [comment]
https://www.studyforrest.org/access.html

**Comment by adswa** [comment]
FWIW, you maybe can base updated instructions on this template: http://handbook.datalad.org/en/latest/basics/101-180-FAQ.html#how-can-i-help-others-get-started-with-a-shared-dataset

**Comment by loj** [comment]
I've submitted a [PR](https://github.com/psychoinformatics-de/studyforrest-www/pull/16) to the website with updated content for the access page based on the template provided by @adswa.

**Comment by loj** [comment]
datasets that need their READMEs updated:
- [x] https://github.com/psychoinformatics-de/studyforrest-data-multires3t ([PR](https://github.com/psychoinformatics-de/studyforrest-data-multires3t/pull/1) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-aggregate ([PR](https://github.com/psychoinformatics-de/studyforrest-data-aggregate/pull/1) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-aligned ([PR](https://github.com/psychoinformatics-de/studyforrest-data-aligned/pull/2) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-perceivedemotions ([PR](https://github.com/psychoinformatics-de/studyforrest-data-perceivedemotions/pull/1) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-eyemovementlabels ([PR](https://github.com/psychoinformatics-de/studyforrest-data-eyemovementlabels/pull/22) submitted)

**Comment by mih** [comment]
THX!
