### ISSUE TITLE
Notebook to explore (parts of) the studyforrest dataset

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/studyforrest-data#42]
I was thinking, after our discussion of adding the "Explore" page to the website, that a relatively easy yet "sparkling" feature might be to link to a computational notebook running in the cloud (e.g. with Binder) that takes the user through some data exploration steps such as:
- Installing the top-level and sub-level datasets with datalad
- `datalad get`ing some sample files
- Some cool visualizations
- Some steps/descriptions/pointers that provide a high-level view on how the data can be processed to generate the existing derivatives
- Perhaps a few other pointers on how to use datalad with the studyforrest dataset

I see this as a nice-to-have, but one that might attract more clicks and interest as well as being educational.

Thoughts?

**Comment by adswa** [comment]
I like the idea!

**Comment by jsheunis** [comment]
i'll create a working example and then we can see where to go from there

**Comment by jsheunis** [comment]
A running version is now available here: https://github.com/jsheunis/studyforrest-data-binder

**Comment by jsheunis** [comment]
This is now running here: https://github.com/psychoinformatics-de/studyforrest-data-binder and was included in the webiste.
