### ISSUE TITLE
Track neurovault collections related to studyforrest data

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/studyforrest-data#43]
@aqw  collections associated with the studyforrest work that I could find on neurovault:

- High-resolution 7-Tesla fMRI data on the perception of musical genres – an extension to the studyforrest dataset: [https://neurovault.org/collections/308/](https://neurovault.org/collections/308/)
- A studyforrest extension, simultaneous fMRI and eye gaze recordings during prolonged natural stimulation:[https://neurovault.org/collections/1065/](https://neurovault.org/collections/1065/)
- Is The PPA a Visual Area? BOLD responses to incidental spatial cues in naturalistic stimulation (<- that was a poster): [https://neurovault.org/collections/5502/](https://neurovault.org/collections/5502/)
- Individual face- and house-related eye movement patterns distinctively activate FFA and PPA: [https://neurovault.org/collections/6075/](https://neurovault.org/collections/6075/)
- Processing of visual and non-visual naturalistic spatial information in the "parahippocampal place area" (<- corresponding paper is in review): [https://neurovault.org/collections/8889/](https://neurovault.org/collections/8889/)

@mih do you know of others?

**Comment by mih** [comment]
I have two more, but they are not worth showing

**Comment by aqw** [comment]
Cool! We can do the 3D view of all of these.

**Comment by aqw** [comment]
All five have been added to explore.html. The content around it needs to be written, but the core functionality is there.

**Comment by adswa** [comment]
Sounds like this can be closed because its done :)
