### ISSUE TITLE
convert READMEs to markdown

### ISSUE THREAD

**Issue by loj** [psychoinformatics-de/studyforrest-data#49]
OpenNeuro and GIN prefer READMEs in markdown

- [x] https://github.com/psychoinformatics-de/studyforrest-data-visualrois ([PR](https://github.com/psychoinformatics-de/studyforrest-data-visualrois/pull/4) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-aligned ([PR](https://github.com/psychoinformatics-de/studyforrest-data-aligned/pull/3) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-retinotopy ([PR](https://github.com/psychoinformatics-de/studyforrest-data-retinotopy/pull/3) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-structural ([PR](https://github.com/psychoinformatics-de/studyforrest-data-structural/pull/5) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-multires7t ([PR](https://github.com/psychoinformatics-de/studyforrest-data-multires7t/pull/7) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-phase2-denoised ([PR](https://github.com/psychoinformatics-de/studyforrest-data-phase2-denoised/pull/2) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-freesurfer ([PR](https://github.com/psychoinformatics-de/studyforrest-data-freesurfer/pull/2) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-templatetransforms ([PR](https://github.com/psychoinformatics-de/studyforrest-data-templatetransforms/pull/2) submitted)
- [x] https://github.com/psychoinformatics-de/studyforrest-data-eyemovementlabels ([PR](https://github.com/psychoinformatics-de/studyforrest-data-eyemovementlabels/pull/23) submitted)

**Comment by adswa** [comment]
AAAAAAAAAAALL MEEEEERGED (:

**Comment by loj** [comment]
Whoohoo! Thanks @adswa!

I think we're good to go, closing.
